CREATE TABLE JUGADOR (
    juga_iden INT(6) UNSIGNED AUTO_INCREMENT UNIQUE PRIMARY KEY,
    juga_nomb VARCHAR(50) NOT NULL,
    juga_apel VARCHAR(50) NOT NULL
);

CREATE TABLE EQUIPO (
    equi_codi INT(6) UNSIGNED AUTO_INCREMENT UNIQUE PRIMARY KEY,
    equi_nomb VARCHAR(50) NOT NULL
);

CREATE TABLE EQUIPOJUGADOR (
    juga_iden INT(6) UNSIGNED,
    equi_codi INT(6) UNSIGNED,
    FOREIGN KEY (juga_iden) REFERENCES JUGADOR(juga_iden),
    FOREIGN KEY (equi_codi) REFERENCES EQUIPO(equi_codi)
);

CREATE TABLE ENCUENTROS (
    numero INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    equi_codi_A INT(6) UNSIGNED,
    equi_codi_B INT(6) UNSIGNED,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    lugar VARCHAR(50),
    FOREIGN KEY (equi_codi_A) REFERENCES EQUIPO(equi_codi),
    FOREIGN KEY (equi_codi_B) REFERENCES EQUIPO(equi_codi)
);